IDENTITY:
  SUBSCRIPTION_ID: ""
  TENANT_ID: ""
  CLIENT_ID: ""
  CLIENT_SECRET: ""
  MSI_ENDPOINT: ""
  MSI_SECRET: ""
  USERNAME: ""
  PASSWORD: ""
  CLIENT_CERTIFICATE_PATH: ""
  AUTHORITY_HOST: ""
PROXY:
  HTTP: ""
  HTTPS: ""
  NO: ""
  ALL: ""
PIPELINE:
  TELEMETRY_DISABLED: ""
  LOG_LEVEL: ""
  TRACING_DISABLED: ""
GENERAL:
  CLOUD: ""
  SUBSCRIPTION_ID: ""
  RESOURCE_GROUP: ""
